### ISSUE TITLE
about the lua syntax highlight 

### ISSUE THREAD

**Issue by finviman** [jcbnlsn/Xcode-Corona-Editor#1]
hi, i use the Add-Lua.sh to give the Xcode ability to highlight lua file syntax. but xcode can not auto detect lua file. every time i open a lua file, i must select Editor->Syntax Coloring->Lua. is there any way to solve this problem?
thanks.

**Comment by jcbnlsn** [comment]
Hi, please read the Readme and you will find the answer. 
I created a couple of behaviour scripts as a workaround for this problem.

**Comment by jcbnlsn** [comment]
This is what the read me says:
NOTE: I didn't yet manage to find a way for Xcode to recognize the .lua file type - meaning that you have to select the lua syntax coloring manually for each file. As a workaround for this I did a couple of behavior scripts to deal with assigning lua syntax coloring. One script for coloring all lua files in current Xcode project and another one for coloring the selected file. You can assign these scripts to keyboard shortcuts via Xcode behaviors to make your life easier. ( See how to below )

If anyone figures out how to register the lua file type in Xcode please let me know. My guess is that something should be modified in the DevToolsCore.framework here: /Applications/Xcode.app/Contents/OtherFrameworks/DevToolsCore.framework/Versions/A/Resources

**Comment by finviman** [comment]
thanks，i find the instruction in Readme.md. i only need the
LuaSyntaxColorProject.applescript,not the

LaunchCoronaSimulator,so i only install the luasyntax behavior followed by
the instruction,but it doesn't work. my Xcode version is 6.1.1.

i find the applescript will replace some snippet like "lastKnownFileType =
sourcecode.lua", but i can't find this pieces in project.pbxproj.

2015-01-08 0:24 GMT+08:00 Jacob Nielsen notifications@github.com:

**Comment by jcbnlsn** [comment]
Hmm.. I am currently running Xcode 6.1 which is working fine. Maybe apple
changed something with how the project.pbxproj is structured in 6.1.1.

I will update  and examine the issue when I get the time.
Thanks.

2015-01-08 5:09 GMT+01:00 acerphoenix notifications@github.com:

**Comment by jcbnlsn** [comment]
Hi, I updated to 6.1.1 but can't recreate your issue. The structure of project.pbxproj seems to be the same as it used to be.
Could you try putting a: display dialog "test" at the top of the apple script to see if the behaviour runs it?
Also could you send a project.pbxproj file to me to inspect?
Thanks

**Comment by finviman** [comment]
hello,i created a new xcode project, added some lua files in source folder.
the attachment is my project.pbxproj.
i only install the Add-Lua.sh. and i can set lua syntax through the
editor->Syntax Coloring menu.
as the pbxproj shows, the lua file has "lastKnownFileType = text" attribute.
thanks.

2015-01-10 20:50 GMT+08:00 Jacob Nielsen notifications@github.com:
